version: '2'
services:
  nginx-api:
    image: nginx
    depends_on:
      - api
    ports:
      - "3001:443"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./api/api.nginx.site:/etc/nginx/conf.d/default.conf
      - ./api/certs/.:/etc/nginx/certs
  api:
    build: api/.
    command: yarn start
    depends_on:
      - db
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: development
      COOKIE_SECRET: ChangeMe1234
    env_file:
      - api/.env
    ports:
      - '8080:3000'
    volumes:
      - ./api/.:/opt/app
      - /opt/app/node_modules
  nginx-frontend:
    image: nginx
    depends_on:
      - frontend
    ports:
      - "3000:443"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./frontend/frontend.nginx.site:/etc/nginx/conf.d/default.conf
      - ./frontend/certs/.:/etc/nginx/certs
  frontend:
    build: frontend/.
    command: yarn start
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NODE_ENV: development
      COOKIE_SECRET: ChangeMe1234
      API_URL: "https://nginx-api"
    ports:
      - "0.0.0.0:3030:3000"
    volumes:
      - ./frontend/.:/opt/frontend
      - /opt/frontend/node_modules
  db:
    build: db/.
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      POSTGRES_PASSWORD: localdev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - '8001:5432'
